import turtle,time,random
x=turtle.Turtle()
y=turtle.Turtle()
z=turtle.Turtle()
z.screen.bgcolor("black")
t=turtle.Turtle()
l=turtle.Turtle()
l.pensize(2)
l.pencolor("yellow")
l.shape("turtle")
l.penup()
l.goto(-160,60)
t.pensize(2)
t.pencolor("red")
t.shape("turtle")
t.penup()
t.goto(-160,100)
turtle.speed(10)
turtle.penup()
turtle.goto(-140,140)
#turtle.write("start")
turtle.pensize(2)
turtle.pencolor("blue")
for i in range(1,10):
  #  turtle.fd(50)
    turtle.write(i,align="center")
    turtle.right(90)
    turtle.forward(10)
    turtle.pendown()
    turtle.fd(150)
    turtle.penup()
    turtle.backward(160)
    turtle.left(90)
    turtle.forward(20)

turtle.pencolor("pink")
turtle.write("finish")
for p in range(50):
    t.forward(random.randint(1,8))
    l.forward(random.randint(1,8))
if t.pos() < l.pos():
    l.pensize(100)
    t.pensize(100)
    l.write("winner")
    t.write("looser")
else:
    l.pensize(100)
    t.pensize(100)
    l.write("looser")
    t.write("winner")
time.sleep(2)